name: alfresco-content-services-community
version: 3.1.1
appVersion: 6.2.0-A11
description: A Helm chart for deploying Alfresco Content Services Community
keywords:
- community
- alfresco community
- content
- content services
- alfresco
- alfresco content services
home: https://www.alfresco.com
sources:
- https://github.com/Alfresco/acs-community-deployment
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
