name: alfresco-content-services-community
version: 6.0.5-01
appVersion: 6.0.5-ea
description: A Helm chart for deploying Alfresco Content Services Community
keywords:
- alfresco
- community
- alfresco community
- content
- content services
home: https://www.alfresco.com
sources:
- https://github.com/Alfresco/acs-community-packaging/tree/master/helm
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
