name: alfresco-content-services-community
version: 6.0.5-01
appVersion: 6.0.5-ea
deprecated: true
description: A Helm chart for deploying Alfresco Content Services Community
keywords:
- community
- alfresco community
- content
- content services
- alfresco
- alfresco content services
home: https://www.alfresco.com
sources:
- https://github.com/Alfresco/acs-community-deployment
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
